//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.UTMatrix {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.UTMatrix.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    2.000   1.000
        ///  -3.000   0.000
        ///   4.000  -1.000
        ///.
        /// </summary>
        internal static string TextA {
            get {
                return ResourceManager.GetString("TextA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Matrix row=&quot;3&quot; col=&quot;2&quot;&gt;
        ///  &lt;TR row=&quot;0&quot;&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;0&quot; val=&quot;2&quot; /&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;1&quot; val=&quot;1&quot; /&gt;
        ///  &lt;/TR&gt;
        ///  &lt;TR row=&quot;1&quot;&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;0&quot; val=&quot;-3&quot; /&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;1&quot; val=&quot;0&quot; /&gt;
        ///  &lt;/TR&gt;
        ///  &lt;TR row=&quot;2&quot;&gt;
        ///    &lt;TD row=&quot;2&quot; col=&quot;0&quot; val=&quot;4&quot; /&gt;
        ///    &lt;TD row=&quot;2&quot; col=&quot;1&quot; val=&quot;-1&quot; /&gt;
        ///  &lt;/TR&gt;
        ///&lt;/Matrix&gt;.
        /// </summary>
        internal static string XML_A {
            get {
                return ResourceManager.GetString("XML_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Matrix row=&quot;2&quot; col=&quot;3&quot;&gt;
        ///  &lt;TR row=&quot;0&quot;&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;0&quot; val=&quot;5&quot; /&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;1&quot; val=&quot;-1&quot; /&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;2&quot; val=&quot;6&quot; /&gt;
        ///  &lt;/TR&gt;
        ///  &lt;TR row=&quot;1&quot;&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;0&quot; val=&quot;-3&quot; /&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;1&quot; val=&quot;0&quot; /&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;2&quot; val=&quot;7&quot; /&gt;
        ///  &lt;/TR&gt;
        ///&lt;/Matrix&gt;.
        /// </summary>
        internal static string XML_B {
            get {
                return ResourceManager.GetString("XML_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Matrix row=&quot;3&quot; col=&quot;2&quot;&gt;
        ///  &lt;TR row=&quot;0&quot;&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;0&quot; val=&quot;2&quot; /&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;1&quot; val=&quot;1&quot; /&gt;
        ///  &lt;/TR&gt;
        ///  &lt;TR row=&quot;1&quot;&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;0&quot; val=&quot;-3&quot; /&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;1&quot; val=&quot;0&quot; /&gt;
        ///  &lt;/TR&gt;
        ///  &lt;TR row=&quot;2&quot;&gt;
        ///    &lt;TD row=&quot;2&quot; col=&quot;0&quot; val=&quot;4&quot; /&gt;
        ///    &lt;TD row=&quot;2&quot; col=&quot;1&quot; val=&quot;-1&quot; /&gt;
        ///  &lt;/TR&gt;
        ///&lt;/Matrix&gt;.
        /// </summary>
        internal static string XML_C {
            get {
                return ResourceManager.GetString("XML_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Matrix row=&quot;3&quot; col=&quot;2&quot;&gt;
        ///  &lt;TR row=&quot;0&quot;&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;0&quot; val=&quot;11&quot; /&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;1&quot; val=&quot;21&quot; /&gt;
        ///  &lt;/TR&gt;
        ///  &lt;TR row=&quot;1&quot;&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;0&quot; val=&quot;12&quot; /&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;1&quot; val=&quot;22&quot; /&gt;
        ///  &lt;/TR&gt;
        ///  &lt;TR row=&quot;2&quot;&gt;
        ///    &lt;TD row=&quot;2&quot; col=&quot;0&quot; val=&quot;13&quot; /&gt;
        ///    &lt;TD row=&quot;2&quot; col=&quot;1&quot; val=&quot;23&quot; /&gt;
        ///  &lt;/TR&gt;
        ///&lt;/Matrix&gt;.
        /// </summary>
        internal static string XML_T1 {
            get {
                return ResourceManager.GetString("XML_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Matrix row=&quot;2&quot; col=&quot;3&quot;&gt;
        ///  &lt;TR row=&quot;0&quot;&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;0&quot; val=&quot;11&quot; /&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;1&quot; val=&quot;12&quot; /&gt;
        ///    &lt;TD row=&quot;0&quot; col=&quot;2&quot; val=&quot;13&quot; /&gt;
        ///  &lt;/TR&gt;
        ///  &lt;TR row=&quot;2&quot;&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;0&quot; val=&quot;21&quot; /&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;1&quot; val=&quot;22&quot; /&gt;
        ///    &lt;TD row=&quot;1&quot; col=&quot;2&quot; val=&quot;23&quot; /&gt;
        ///  &lt;/TR&gt;
        ///&lt;/Matrix&gt;.
        /// </summary>
        internal static string XML_T2 {
            get {
                return ResourceManager.GetString("XML_T2", resourceCulture);
            }
        }
    }
}
